Upgrade pydantic
Resolves issue found when using improved type annotations.

Looks like this may be the cause: https://github.com/samuelcolvin/pydantic/issues/2060

$ ./update_prevalence.py
Traceback (most recent call last):
  File "/Users/broz/src/microCOVID/./update_prevalence.py", line 367, in <module>
    class Place(pydantic.BaseModel):
  File "/Users/broz/src/microCOVID/.venv/lib/python3.10/site-packages/pydantic/main.py", line 299, in __new__
    fields[ann_name] = ModelField.infer(
  File "/Users/broz/src/microCOVID/.venv/lib/python3.10/site-packages/pydantic/fields.py", line 411, in infer
    return cls(
  File "/Users/broz/src/microCOVID/.venv/lib/python3.10/site-packages/pydantic/fields.py", line 342, in __init__
    self.prepare()
  File "/Users/broz/src/microCOVID/.venv/lib/python3.10/site-packages/pydantic/fields.py", line 451, in prepare
    self._type_analysis()
  File "/Users/broz/src/microCOVID/.venv/lib/python3.10/site-packages/pydantic/fields.py", line 604, in _type_analysis
    self.type_ = get_args(self.type_)[1]
IndexError: tuple index out of range
$